version: '3.6'

services:

  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html

  loomis-oc:
    build: ./openclinica
    environment:
      - DATABASE_NAME=loomis 
      - DB_HOST=loomis-pg  
    volumes: 
      - loomis_oc-data:/usr/local/tomcat/openclinica.data

  loomis-pg:
    image: postgres:9.5
    environment: 
      - POSTGRES_INITDB_ARGS="-E 'UTF-8'"
      - POSTGRES_PASSWORD=postgres123
    volumes: 
      - loomis_ocdb-data:/var/lib/postgresql/data
      - $PWD/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  panbordex-oc:
    build: ./openclinica
    environment:
      - DATABASE_NAME=panbordex
      - DB_HOST=panbordex-pg
    volumes: 
      - panbordex_oc-data:/usr/local/tomcat/openclinica.data

  panbordex-pg:
    image: postgres:9.5
    environment: 
      - POSTGRES_INITDB_ARGS="-E 'UTF-8'"
      - POSTGRES_PASSWORD=postgres123
    volumes: 
      - panbordex_ocdb-data:/var/lib/postgresql/data
      - $PWD/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  loomis_oc-data:
  loomis_ocdb-data:
  panbordex_oc-data:
  panbordex_ocdb-data:
