version: '3.6'

# Replace ZZZZ with the domain name of the server. If pure
# development, then the 2 /docker-volumes/etc/letsencrypt in the
# nginx-proxy definition  can be deleted.

# Replace XXXX and ZZZZ with the names of the OpenClinica names you want.

services:

  nginx-proxy:
    depends_on:
      - test-oc
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - ./letsencrypt/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/test/fullchain.pem:/etc/letsencrypt/live/test/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/test/privkey.pem:/etc/letsencrypt/live/test/privkey.pem
    restart: unless-stopped

  test-oc:
    depends_on:
      - test-pg
    build: ./openclinica
    environment:
      - DATABASE_NAME=test 
      - DB_HOST=test-pg  
    volumes: 
      - test_oc-data:/usr/local/tomcat/openclinica.data
    restart: unless-stopped

  test-pg:
    image: postgres:9.5
    environment: 
      - POSTGRES_INITDB_ARGS="-E 'UTF-8'"
      - POSTGRES_PASSWORD=postgres123
    volumes: 
      - test_ocdb-data:/var/lib/postgresql/data
      - $PWD/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: unless-stopped

volumes:
  test_oc-data:
  test_ocdb-data:
