version: '3.6'

services:
  loomis-oc:
    image: piegsaj/openclinica
    env_file: loomis_oc.env
    volumes: 
      - loomis_oc-data:/usr/local/tomcat/openclinica.data
    ports: 
      - 80:8080
  loomis-pg:
    image: postgres:9.5
    env_file: loomis_pg.env
    ports: 
      - 5432:5432
    volumes: 
      - loomis_ocdb-data:/var/lib/postgresql/data
      - $PWD/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
volumes:
  loomis_oc-data:
  loomis_ocdb-data: