version: '3.6'

services:

  ngix-proxy:
    container_name: ngix-proxy
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    networks:
      - loomis-network

  loomis-oc:
    container_name: loomis-oc
    image: piegsaj/openclinica
    environment:
      - LOG_LEVEL=INFO
      - TZ=UTC-1
      - DB_TYPE=postgres 
      - DB_HOST=loomis-pg
      - DB_NAME=openclinica
      - DB_USER=clinica
      - DB_PASS=clinica 
      - DB_PORT=5432
      - SUPPORT_URL="https://www.openclinica.com/community-edition-open-source-edc/" \ 
    volumes: 
      - loomis_oc-data:/usr/local/tomcat/openclinica.data
    ports: 
      - 80:8080
    networks: 
      - loomis-network

  loomis-pg:
    container_name: loomis-pg
    image: postgres:9.5
    environment: 
      - POSTGRES_INITDB_ARGS="-E 'UTF-8'"
      - POSTGRES_PASSWORD=postgres123
    ports: 
      - 5432:5432
    volumes: 
      - loomis_ocdb-data:/var/lib/postgresql/data
      - $PWD/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks: 
      - loomis-network

volumes:
  loomis_oc-data:
  loomis_ocdb-data:

networks: 
  loomis-network:
    driver: bridge